name: Schedule Test

on:
  schedule:
    - cron: "25 14 * * *"
      timezone: "America/Chicago"
    - cron: "30 14 * * *"
      timezone: "America/Chicago"
  workflow_dispatch:


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger info
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "schedule=${{ github.event.schedule }}"
          date
          TZ="America/Chicago" date

  two-twenty-five:
    if: github.event.schedule == '25 14 * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from 2:25 PM Central"

  two-thirty:
    if: github.event.schedule == '30 14 * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from 2:30 PM Central"