name: Schedule Test

on:
  schedule:  
    - cron: "49 20 * * *"
    - cron: "53 20 * * *"

  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger info
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "schedule=${{ github.event.schedule }}"
          date
          TZ="America/Chicago" date

  job-1:
    if: github.event.schedule == '49 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World Job1"

  job-2:
    if: github.event.schedule == '53 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World Job2"